Fix code example error at Guard
Changes:

1. `case Point(x, y) if x == y:` -> `case Point(x=x, y=y) if x == y:`
2. `case Point(x, y):` -> `case Point(x=x, y=y):`

The original code will give the following error because class `Point` defined above is not a dataclass and has no `__match_args__` as the [doc](https://docs.python.org/3.10/whatsnew/3.10.html#patterns-with-positional-parameters) says:

```python
Traceback (most recent call last):
  File "/root/test.py", line 69, in <module>
    guard_test(point)
  File "/root/test.py", line 39, in guard_test
    case Point1(x, y) if x == y:
TypeError: Point1() accepts 0 positional sub-patterns (2 given)
```