asyncio.streams.open_connection remove loop from docstring
asyncio.streams.open_connection no longer accepts loop as a
keyword argument and providing it causes:
TypeError: BaseEventLoop.create_connection() got an unexpectedkeyword argument 'loop'
therefore remove it from the docstring.