Fix the eq check that is used in absence of `__contains__`
Both the `__iter__` and the index-iteration method test the `is` first. While the document says that `x is x` means that `x == x` should be true, it is not true for example in the case of `nan`. 

```>>> x = float('nan') 
>>> x == x
False
>>> x is x
True
>>> class Foo:
...     def __iter__(self):
...         return iter([x])
... 
>>> x in Foo()
True
>>> any(x == i for i in Foo())
False
>>> class Bar:
...     def __getitem__(self):
...         return [x].__getitem__(self)
... 
>>> class Bar:
...     def __getitem__(self, i):
...         return [x].__getitem__(i)
... 
>>> x in Bar
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: argument of type 'type' is not iterable
>>> x in Bar()
True
>>> any(x == i for i in Bar())
False```