bpo-32374: Enhance test_importlib.test_bad_traverse()
Make test_bad_traverse() fails if the script raises a Python
exception: generic exit code 1. The test expects a crash which means
an exit code different than 0 and 1.