bpo-35038: AttributeError: 'frame' object has no attribute 'f_restricted'. (GH-10098)
https://bugs.python.org/issue35038
(cherry picked from commit 1770d1c5121ed6c64d7072875738f97e07eede8a)

Co-authored-by: Stéphane Wirtel <stephane@wirtel.be>