Remove failing NEWS file
In the original PR (25288), which this PR replaces, I asked several
questions, including:

1. The checks complain that "skip issue" and skip news" labels are miissing. How do I add labels?
2. What does it mean for the checks to report that required checks have been skipped.
3. I have examined the logs from the "Docs PR - Build documentation" pre-build check. What does this error mean, and what was I supposed to have done to avoid it?

```
2021-04-08T22:28:01.3554327Z Warning, treated as error:
2021-04-08T22:28:01.3556468Z /home/vsts/work/1/s/Doc/using/configure.rst:416:unknown option: --enable-universalsdk
2021-04-08T22:28:03.8447865Z Makefile:49: recipe for target 'build' failed
2021-04-08T22:28:03.8481903Z make: *** [build] Error 2
2021-04-08T22:28:03.8538418Z ##[error]Bash exited with code '2'.
```

All of my questions were ignored. This PR ran into some of the same failures.
I tried to correct the missing "skip news" label by clicking on the "Details"
link, which took me to a page where I was asked to register my GitHub account
with a tool called "blurb_it" which in turn presented me with a form asking
for an issue number and a PR number. There is no issue number, as my
understanding is that for some PRs (such as minor documentation corrections)
it is inappropriate to create a GitHub issue. Nevertheless, the form requires
that the issue number field not be left blank, so I entered "none" and
submitted the form again, and it was accepted. Now, however, the PR build is
failing with the following error message:
```
ValueError: invalid literal for int() with base 10: 'none'
```
So I am removing the news file to eliminate this error.

It would be awesome if I could get some answers to the questions above.