[3.8] bpo-40431: Fix syntax typo in turtledemo (GH-19777)
***   File "/usr/lib64/python3.9/turtledemo/__main__.py", line 275
        bg="GH-d00" if clear == NORMAL else"GH-fca")
                                        ^
    SyntaxError: invalid string prefix
(cherry picked from commit 49f70db83e2c62ad06805927f53f6c3e8f4b798e)

Co-authored-by: Miro Hrončok <miro@hroncok.cz>