fixing (import Mapping from collections), issue #91639
Concerning python 3.10, the following error occurs for scripts trying to import `Mapping` from `collections`

### Error:
`
ImportError: cannot import name 'Mapping' from 'collections' (/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/collections/__init__.py
`
### Proposed Solution:
add the following line to the `collections/__init__.py`
**Line :** `from collections.abc import Mapping`

### Reason:
Python scripts using the `collections` library form older versions would face problems when updating to **python 3.10**