Add soft-deprecated to site-packages
Fixes #155095

make -C Doc changes

File "/home/cbot/.local/lib/python3.14/site-packages/sphinx/builders/changes.py", line 61, in write_documents
        ttext = self.typemap[changeset.type]
                ~~~~~~~~~~~~^^^^^^^^^^^^^^^^
    KeyError: 'soft-deprecated'