Update cgi.py
When using web.py, I get the following failure:
```
  File "/usr/local/lib/python3.5/dist-packages/web/webapi.py", line 364, in input
    out = rawinput(_method)
  File "/usr/local/lib/python3.5/dist-packages/web/webapi.py", line 341, in rawinput
    a = cgi.FieldStorage(fp=fp, environ=e, keep_blank_values=1)
  File "/usr/lib/python3.5/cgi.py", line 561, in __init__
    self.read_single()
  File "/usr/lib/python3.5/cgi.py", line 740, in read_single
    self.read_binary()
  File "/usr/lib/python3.5/cgi.py", line 762, in read_binary
    self.file.write(data)
TypeError: write() argument must be str, not bytes
```
Converting data to a string using the str() function fixes the problem.  There may be a better way to transform data to a string, but it seems to need to happen one way or another.