asyncio: don't do anything in _SelectorDatagramTransport if we're closed
It could happen that the transport's sendto() method is invoked after
the transport was closed. Closing the transport sets the _sock attribute
to None, which then causes the following exception:

    Traceback (most recent call last):
      File "/usr/lib/python3.9/asyncio/selector_events.py", line 1056, in sendto
	self._sock.sendto(data, addr)
    AttributeError: 'NoneType' object has no attribute 'sendto'

So just check if we're closed before doing anything, similarly to what we already
do in other methods.