doc-files should break files up into multiple lines, as per RPM expectation
when using %doc section of the RPM spec, it expects multiple files
to be listed each on their own line.  Currently what gets passed in
is:

%doc file1 file2 file3

which throws:
	error: More than one file on a line: file1
	error: More than one file on a line: file2
	error: More than one file on a line: file3

This breaks the files up into seperate lines:

%doc
file1
file2
file3

which works as expected with multiple files

Signed-off-by: John 'Warthog9' Hawley <jhawley@vmware.com>
Signed-off-by: John 'Warthog9' Hawley <warthog9@eaglescrag.net>