configure.ac: define a path for profile data
There comes below error when use ccache 3.7.10 to compile python3
and check [1] for more details.
 | Python-3.8.3/Modules/_contextvarsmodule.c:43:1: error: source locations for function 'PyInit__contextvars' have changed, the profile data may be out of date [-Werror=coverage-mismatch]

That's because the logic for profile directory changes a little in
[2] after ccache upgrades to 3.7.10 and it errors out if no profile
data found per [2] and [3].

So define a profile directory path accordingly to fix the above error.

[1] https://github.com/ccache/ccache/issues/615
[2] https://github.com/ccache/ccache/commit/c9fdcef576dd13a2ea2355bcd866b5c561cb1562
[3] https://github.com/ccache/ccache/commit/91a2954eb47b4a106e2be6cf611917b895108e35

Signed-off-by: Mingli Yu <mingli.yu@windriver.com>