Provide location info on SyntaxError due to EOLS or EOFS errors (#60)
The current parser outputs a position pointer, when an EOLS or
EOFS error occurs, while parsing. With this, we imitate this
behavior:
>>> a = 'ex
  File "<stdin>", line 1
    a = 'ex
             ^
SyntaxError: EOL while scanning string literal