Move the fuzzer to C++ so that it builds.
It's possible there's a way to compile this with clang and then link it with
clang++, but I don't know how to do that.

Specifically, compilation fails with this:

    $CC $CFLAGS \
        -D _Py_FUZZ_ONE -D _Py_FUZZ_$fuzz_test \
        -Wno-unused-function \
        $($OUT/bin/python3-config --cflags) -g -O1 \
        $FUZZ_DIR/fuzzer.c -o $OUT/$fuzz_test -lFuzzingEngine \
        $($OUT/bin/python3-config --ldflags)

With errors like:

    /usr/local/bin/../include/c++/v1/new:234: undefined reference to `operator delete(void*)'

But it works just fine with this:

    $CXX $CXXFLAGS \
        -D _Py_FUZZ_ONE -D _Py_FUZZ_$fuzz_test \
        -Wno-unused-function \
        $($OUT/bin/python3-config --cflags) -g -O1 \
        $FUZZ_DIR/fuzzer.c -o $OUT/$fuzz_test -lFuzzingEngine \
        $($OUT/bin/python3-config --ldflags)

Presumably there are ways to do this in C, so for expediency I'm doing it in C++
right now, with the minimal possible C++ changes (extern "C"), so that if I need
to change it back to C in code review, it won't be too hard.