gh-99597: Better error message for assignment in f-strings
The introduction of debug f-strings in 3.8 regressed the error message
users would get here.

```
$ python3.7 -c 'f"{x = 5}"'
  File "<fstring>", line 1
    (x = 5)
       ^
SyntaxError: invalid syntax
```

```
$ python3.9 -c 'f"{x = 5}"'
  File "<string>", line 1
    f"{x = 5}"
              ^
SyntaxError: f-string: expecting '}'
```

This adds a little bit of special casing to the f-string specific logic
in order to provide a better error message:

```
$ ./python.exe -c 'f"{x = 5}"'
  File "<string>", line 1
    f"{x = 5}"
              ^
SyntaxError: f-string: expected expression, not assignment statement
```