[3.15] gh-149044: Avoid C++ warnings in PySlot_END macro (GH-158866) (#158965)
gh-149044: Avoid C++ warnings in PySlot_END macro (GH-158866)

Initialize all fields in the macro. Otherwise, g++ -Wall -Wextra
complains that some fields are not initialized
[-Werror=missing-field-initializers]:

  error: missing initializer for member ‘PySlot::sl_flags’
  error: missing initializer for member ‘PySlot::<anonymous>’
  error: missing initializer for member ‘PySlot::<anonymous>’
(cherry picked from commit ba9d96ff8d7c572a0c90f072102d54b1fc3044dc)

Co-authored-by: Victor Stinner <vstinner@python.org>