Add unicodedata.aliases()
In some situations, you have a character and you want a human-readable
description of that character. For example, I was writing some code that
parses a certain file format. In that file format, you are not allowed
to use certain characters. I wanted to be able to show the user an error
that looked something like this if the user used one of the banned
characters:

    ERROR: You’re not allowed to use U+0000 NULL characters.

For most characters, you can use unicodedata.name() in order to get a
human-readable description of that character. Unfortunately,
unicodedata.name() does not work for U+0000 because U+0000 and many
other characters do not have names. In order to get a human-readable
description of U+0000, you need to look up its name aliases.

Before this change, you could turn an alias into a character (via
"\N{…}" and unicodedata.lookup()), but there was no way to turn a
character into its aliases. This change adds a new unicodedata.aliases()
function that allows you to turn a character into its aliases.

This commit implements gh-62434. In that thread, there were many
different proposals for potential ways to expose this data to Python
programs. This commit most closely matches flying-sheep’s proposal [1].
Here are the differences between what’s implemented in this commit, and
what flying-sheep proposed:

• flying-sheep proposed that unicodedata.aliases() would have an
  optional type argument that could be used to filter the output by
  alias type. The version of unicodedata.aliases() added by this commit
  does not include an optional type argument. You can already filter the
  output to your liking by simply using the returned dictionary. In
  other words, unicodedata.aliases("\n", type="control") would have been
  the same as unicodedata.aliases("\n")["control"]. Based on that fact,
  having an optional type argument didn’t seem very useful.

• flying-sheep proposed that the return value would use the dict, str
  and list data types. Two of those data types are mutable and one is
  immutable. This commit uses the frozendict, str and tuple data types.
  All three of those data types are immutable which is more consistent.
  Plus, the purpose unicodedata.aliases() is to lookup data that can be
  used later, not to create something that will later be modified. (I
  mean, you could theoretically modify the dict or the lists that
  flying-sheep’s proposal would have returned, but why would you?)

[1]: <https://github.com/python/cpython/issues/62434#issuecomment-1093619281>